### ISSUE TITLE
Error while connecting to mysql

### ISSUE THREAD

**Issue by ajayRam2020** [tvntsr/push#4]
Hi, When I am starting kamailio, I am getting below error.

ERROR: push [push_common.c:406]: push_check_db(): Database module does not implement all functions needed by push module

ERROR: push [push_mod.c:290]: mod_init(): Cannot connect database, failed
./kamailio[14400]: ERROR: <core> [sr_module.c:968]: init_mod(): Error while initializing module push (/usr/local/kamailio/lib64/kamailio/modules/push.so)

Modparam settings: [username and password are correct.]

modparam("push", "push_db", "mysql://kamailio:kamailiorw@localhost/kamailio")

**Comment by norwood-dw** [comment]
I saw this while using PostGres on Ubuntu 16.

Seemed to go away after I fixed this:

```
push_common.c: In function ‘create_push_server’:
push_common.c:355:5: warning: ‘memset’ used with constant zero length parameter; this could be due to transposed parameters [-Wmemset-transposed-args]
     memset(&server->dbf, sizeof(server->dbf), 0);
```

**Comment by kangzhonghua** [comment]
memset(&server->dbf, sizeof(server->dbf), 0);===>memset(&server->dbf, 0, sizeof(server->dbf));

**Comment by tvntsr** [comment]
Thanks, fixed.
This error: "ERROR: push [push_common.c:406]: push_check_db(): Database module does not implement all functions needed by push module" means that DB does not have proper table created, check please push.sql
