### ISSUE TITLE
Support for Google Cloud Messeging (progress)

### ISSUE THREAD

**Issue by nicopace** [tvntsr/push#6]
Hi,

I wanted to open this issue to ask you if you have a roadmap where you plan to add GCM support and when, if possible.
Not being pushy, just want to know if this is a viable way of doing push notifications to Android clients or perhaps need to dig into other solutions.

Thanks!

**Comment by tvntsr** [comment]
There is a plan to add it. 
I will start working on it in summer...

**Comment by nicopace** [comment]
@tvntsr would be awesome to leave the issue open till it get's done... so anyone that is interested on the issue can get notified on any progress :) would love to help you testing it... need to do it now and had to seek other ways to solve it
