### ISSUE TITLE
Example of configuration functions

### ISSUE THREAD

**Issue by fuzhenguo** [tvntsr/push#9]
Hi,

We're recently integrating the Push into Kamailio, and we have done the parameters' configuration. Now we are struggling with the functions you mentioned in the Readme. Could you pls kindly give any example kamailio.cfg for the functions of push library. Thank you so much.

Regards,
Jacob

**Comment by AmineMansouriLondon** [comment]
I know it's a long shot but did you get this working? I am a novice and these functions are just so confusing.

**Comment by fuzhenguo** [comment]
#!ifdef WITH_PUSH
loadmodule "push.so"

#!ifdef WITH_PUSH
# ----- push params -----
modparam("push", "push_db", DBURL)
modparam("push", "push_table", "push_apns")
modparam("push", "push_flag", 0)
modparam("push", "push_apns_cert", "/usr/local/kamailio-5.0/etc/kamailio/VOIP.pem")
modparam("push", "push_apns_key", "/usr/local/kamailio-5.0/etc/kamailio/VOIP-key.pem")
modparam("push", "push_apns_cafile", "/usr/local/kamailio-5.0/etc/kamailio/VOIP-ca.pem")
modparam("push", "push_apns_server", "gateway.sandbox.push.apple.com")
modparam("push", "push_apns_port", 2195)
modparam("push", "push_apns_rtimeout", 10000)
#!endif

# ----- Handle SIP registrations -----
route[REGISTRAR] {
	if (!is_method("REGISTER")) return;

	if(isflagset(FLT_NATS)) {
		setbflag(FLB_NATB);
#!ifdef WITH_NATSIPPING
		# do SIP NAT pinging
		setbflag(FLB_NATSIPPING);
#!endif
	}
	if (!save("location")) {
		sl_reply_error();
	} 
#!ifdef WITH_PUSH
	else {
		# push notification service
		route(PUSH);
	}
#!endif
	exit;
}


#!ifdef WITH_PUSH
route[PUSH] {
	reg_fetch_contacts("location", "$fu", "callee");

	$var(token)=$(ct{param.value, pn-tok});
        xlog("Contact: $ct\n token: $var(token)");
	if ($var(token)!=$null){
            push_register($(ct{param.value, pn-tok}));
	}
}
#!endif

# Notice the ct{param.value, pn-tok} should be added in the iOS code side before the registration with Kamailio server.
